import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

interface AppState {
  messages: Array<{ role: string; text: string }>;
  hosts: Array<{ id: string; connected: boolean }>;
  workspaces: Array<{ id: string; name: string }>;
  runs: Array<{ status: string }>;
  commands: Array<{ type: string; status: string }>;
  artifacts: Array<{ kind: string; metadata: Record<string, unknown> }>;
}

async function waitFor<T>(label: string, fn: () => Promise<T | undefined>, timeoutMs = 10_000): Promise<T> {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    try {
      const value = await fn();
      if (value !== undefined) {
        return value;
      }
    } catch {
      // Retry until the timeout while the subprocesses are still starting.
    }

    await new Promise((resolveSleep) => setTimeout(resolveSleep, 200));
  }

  throw new Error(`Timed out waiting for ${label}`);
}

async function getState(port: number): Promise<AppState> {
  const response = await fetch(`http://127.0.0.1:${port}/api/state`);
  if (!response.ok) {
    throw new Error(`Unexpected state response ${response.status}`);
  }

  return (await response.json()) as AppState;
}

async function postMessage(port: number, body: Record<string, unknown>): Promise<void> {
  const response = await fetch(`http://127.0.0.1:${port}/api/messages`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!response.ok && response.status !== 202) {
    throw new Error(`Unexpected message response ${response.status}: ${await response.text()}`);
  }
}

function spawnLogged(command: string, args: string[], cwd: string): ChildProcess {
  const child = spawn(command, args, {
    cwd,
    env: process.env,
    stdio: ["ignore", "pipe", "pipe"],
  });

  child.stdout.on("data", (chunk) => process.stdout.write(`[${command}] ${chunk}`));
  child.stderr.on("data", (chunk) => process.stderr.write(`[${command}] ${chunk}`));
  return child;
}

async function stopProcess(child: ChildProcess): Promise<void> {
  if (child.exitCode !== null) {
    return;
  }

  child.kill("SIGTERM");
  await new Promise((resolveStop) => child.once("exit", () => resolveStop(undefined)));
}

const repoRoot = resolve(process.cwd());
const port = 4318;
const stateDir = await mkdtemp(join(tmpdir(), "pluto-state-"));
const stateFile = join(stateDir, "state.json");
const workspaceRoot = await mkdtemp(join(tmpdir(), "pluto-workspace-"));

await mkdir(resolve(workspaceRoot, "notes"), { recursive: true });
await writeFile(resolve(workspaceRoot, "notes/hello.txt"), "hello from pluto\n", "utf8");

const master = spawnLogged("npx", ["tsx", "src/bin/master.ts", "--port", String(port), "--state-file", stateFile], repoRoot);
let host: ChildProcess | undefined;

try {
  await waitFor("master health", async () => {
    const response = await fetch(`http://127.0.0.1:${port}/healthz`);
    return response.ok ? true : undefined;
  });

  host = spawnLogged(
    "npx",
    [
      "tsx",
      "src/bin/host.ts",
      "--master-url",
      `http://127.0.0.1:${port}`,
      "--host-id",
      "laptop",
      "--host-name",
      "Laptop",
      "--workspace",
      `repo=${workspaceRoot}`,
    ],
    repoRoot,
  );

  await waitFor("host registration", async () => {
    const state = await getState(port);
    return state.hosts.some((hostRecord) => hostRecord.id === "laptop" && hostRecord.connected) ? state : undefined;
  });

  await postMessage(port, {
    text: "Write a file on the laptop workspace.",
    commandType: "workspace.write_file",
    workspaceId: "laptop:repo",
    payload: {
      path: "notes/generated.txt",
      content: "generated by smoke test\n",
    },
  });

  await waitFor("write_file completion", async () => {
    const state = await getState(port);
    return state.commands.some((command) => command.type === "workspace.write_file" && command.status === "completed")
      ? state
      : undefined;
  });

  await postMessage(port, {
    text: "Read the generated file back.",
    commandType: "workspace.read_file",
    workspaceId: "laptop:repo",
    payload: {
      path: "notes/generated.txt",
    },
  });

  await postMessage(port, {
    text: "Run a shell command inside the workspace.",
    commandType: "process.run",
    workspaceId: "laptop:repo",
    payload: {
      command: "cat",
      args: ["notes/generated.txt"],
      cwd: ".",
    },
  });

  const finalState = await waitFor("process.run completion", async () => {
    const state = await getState(port);
    const hasProcessRun = state.commands.some((command) => command.type === "process.run" && command.status === "completed");
    return hasProcessRun ? state : undefined;
  });

  const hasGeneratedArtifact = finalState.artifacts.some((artifact) => artifact.metadata.relativePath === "notes/generated.txt");
  const hasCommandOutput = finalState.artifacts.some((artifact) => artifact.metadata.stdout === "generated by smoke test");

  if (!hasGeneratedArtifact || !hasCommandOutput) {
    throw new Error("Smoke test did not produce the expected artifacts.");
  }

  console.log("Smoke test passed.");
} finally {
  if (host) {
    await stopProcess(host);
  }
  await stopProcess(master);
}
